name: dialect # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Translate between languages
description: |
  A translation app for GNOME.
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
compression: lzo
grade: stable
contact: soumyadeepghosh2004@zohomail.in
architectures:
  - build-on: amd64

plugs:
  dialect-svc:
    bus: session
    interface: dbus
    name: app.drey.Dialect
parts:
  dialect:
    after: [gtts]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/dialect-app/dialect.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    meson-parameters:
      - --prefix=/snap/dialect/current/usr
    build-packages:
      - blueprint-compiler
      - libgstreamer1.0-dev
    stage-packages:
      - python3-gst-1.0
      - libgstreamer1.0-0
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/dialect/current/usr/bin/dialect"
    override-stage: |
      craftctl default
      sed -e 's|Icon=app.drey.Dialect|Icon=/usr/share/icons/hicolor/scalable/apps/app.drey.Dialect.svg|' -i usr/share/applications/app.drey.Dialect.desktop
    organize:
      # WORKAROUND: Move files from fake installation location to actual target
      snap/dialect/current/usr: usr
    parse-info: [usr/share/metainfo/app.drey.Dialect.metainfo.xml]
  gtts:
    plugin: python
    source: https://github.com/pndurette/gTTS.git
    source-tag: v2.3.1
    #build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
     # - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
     # - PYTHONPATH: ""
    python-packages:
      - dbus-python
      - urllib3
      - idna
      - charset-normalizer
      - certifi
      - requests
      - click
      - PyGObject
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - dialect
      - gtts
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gnome-42-2204-sdk
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gnome-42-2204-sdk"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  dialect:
    command: usr/bin/dialect
    extensions: [gnome]
    common-id: app.drey.Dialect
    desktop: usr/share/applications/app.drey.Dialect.desktop
    plugs:
      - home
      - network
      - network-status
      - dialect-svc
