name: dialect # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Translate between languages
description: |
  A translation app for GNOME.
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0+
compression: lzo
contact: soumyadeepghosh2004@zohomail.in
architectures:
  - build-on: amd64
    build-for: amd64

plugs:
  dialect-svc:
    bus: session
    interface: dbus
    name: app.drey.Dialect
parts:
  dialect:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://github.com/dialect-app/dialect.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - blueprint-compiler
      - libgstreamer1.0-dev
    stage-packages:
      - libgstreamer1.0-0
  gtts:
    plugin: python
    source: https://github.com/pndurette/gTTS.git
    source-tag: v2.3.1
    python-packages:
      - dbus-python
      - urllib3
      - idna
      - charset-normalizer
      - certifi
      - requests
      - click
      - PyGObject
apps:
  dialect:
    command: usr/bin/dialect
    extensions: [gnome]
    common-id: app.drey.Dialect
    #desktop: gui/saber.desktop
    plugs:
      - home
      - network
      - dialect-svc
